workflows:
  android-release:
    scripts:
      - name: Build Android App Bundle
        working_directory: android
        script: ./gradlew bundleRelease
    artifacts:
      - build/**/outputs/bundle/**/*.aab
